# fly.toml app configuration file generated for continuous-insight-api on 2024-11-19T10:05:21Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'continuous-insight-api'
primary_region = 'lhr'

[build]
  dockerfile = "Dockerfile"

[deploy]
  release_command = "alembic upgrade head"

[mounts]
  source = "sqlite_data"
  destination = "/app/database"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  PYTHONPATH = "/app"
